version: '3.4'

services:
  frontend:
    build:
      context: ./ui
      target: node-stage
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
    command: sh -c "python manage.py migrate && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DATABASE_URL=sqlite:////opt/app/db.sqlite3
    volumes:
       - ./db.sqlite3:/opt/app/db.sqlite3
