version: '3.4'

services:
  # nginx:
  #   image: nginx:1.19-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    build:
      context: ./ui
      target: node-stage
    ports:
      - "8080:8080"
    # volumes:
    #   - ./ui/src:/opt/app/src:ro

  backend:
    build:
      context: ./backend
    command: sh -c "python manage.py migrate && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"
    # depends_on:
    #   - postgres
    # env_file:
    #   - ./backend.env
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DATABASE_URL=sqlite:////opt/app/db.sqlite3
    volumes:
       - ./db.sqlite3:/opt/app/db.sqlite3
    # volumes:
    #   - ./backend/ldfinance:/opt/app/ldfinance

  # postgres:
  #   image: postgres:13-alpine
  #   env_file:
  #     - ./postgres.env
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
